export type MainTableType = {
  id: number;
  created_at: string;
  utm_url: string;
  utm_campaign_id: string;
  utm_source: string;
  utm_medium: string;
  utm_campaign_name: string | null;
  utm_term: string | null;
  utm_content: string | null;
  utm_memo: string | null;
  full_url: string;
  shorten_url: string;
};

export const defaultDataList: Array<MainTableType> = [
  {
    id: 1,
    created_at: '2023.02.22',
    utm_url: 'www.vava.com',
    utm_campaign_id: 'camapign ID',
    utm_source: 'dde',
    utm_medium: 'medium',
    utm_campaign_name: '2020_performance.com',
    utm_term: 'imgae1',
    utm_content: '1234325',
    utm_memo:
      'utm 필요alj하다2222222222222222222een2ne2ne2mnem2neen2mne2ne2n,2men,2men,2men2,emn,2men2ne',
    full_url: 'https://shop.com.ke',
    shorten_url: 'https://cococo.com',
  },
  {
    id: 28888,
    created_at: '2023.04.23',
    utm_url: 'www.vava.com',
    utm_campaign_id: 'camapign ID',
    utm_source: 'afaace',
    utm_medium: 'medium',
    utm_campaign_name: '2020_performance.com',
    utm_term: 'imgae1',
    utm_content: '1234325',
    utm_memo: 'utm 필요하wqe다',
    full_url: 'https://shop.com.ke',
    shorten_url: 'https://cococo.com',
  },
  {
    id: 3123566,
    created_at: '2023.09.24',
    utm_url: 'www.nn.com',
    utm_campaign_id: 'camapign ID',
    utm_source: 'sceedce',
    utm_medium: 'medium',
    utm_campaign_name: '2020_performance.com',
    utm_term: 'imgae1',
    utm_content: '1234325',
    utm_memo: 'utm 필요dsf하다',
    full_url: 'https://shop.com.ke',
    shorten_url: 'https://cococo.com',
  },
  {
    id: 31112323,
    created_at: '2023.08.22',
    utm_url: 'www.nn.com',
    utm_campaign_id: 'camapign ID',
    utm_source: 'sceedce',
    utm_medium: 'medium',
    utm_campaign_name: '2020_performance.com',
    utm_term: 'imgae1',
    utm_content: '1234325',
    utm_memo: 'utm 필요dsf하다',
    full_url: 'https://shop.com.ke',
    shorten_url: 'https://cococo.com',
  },
  {
    id: 3556,
    created_at: '2023.02.24',
    utm_url: 'www.nn.com',
    utm_campaign_id: 'camapign ID',
    utm_source: 'sceedce',
    utm_medium: 'medium',
    utm_campaign_name: '2020_performance.com',
    utm_term: 'imgae1',
    utm_content: '1234325',
    utm_memo: 'utm 필요dsf하다',
    full_url: 'https://shop.com.ke',
    shorten_url: 'https://cococo.com',
  },
  {
    id: 3122,
    created_at: '2023.02.24',
    utm_url: 'www.nn.com',
    utm_campaign_id: 'camapign ID',
    utm_source: 'sceedce',
    utm_medium: 'medium',
    utm_campaign_name: '2020_performance.com',
    utm_term: 'imgae1',
    utm_content: '1234325',
    utm_memo: 'utm 필요dsf하다',
    full_url: 'https://shop.com.ke',
    shorten_url: 'https://cococo.com',
  },
  {
    id: 3111,
    created_at: '2023.02.24',
    utm_url: 'www.nn.com',
    utm_campaign_id: 'camapign ID',
    utm_source: 'sceedce',
    utm_medium: 'medium',
    utm_campaign_name: '2020_performance.com',
    utm_term: 'imgae1',
    utm_content: '1234325',
    utm_memo: 'utm 필요dsf하다',
    full_url: 'https://shop.com.ke',
    shorten_url: 'https://cococo.com',
  },
  {
    id: 32434,
    created_at: '2023.02.24',
    utm_url: 'www.nn.com',
    utm_campaign_id: 'camapign ID',
    utm_source: 'sceedce',
    utm_medium: 'medium',
    utm_campaign_name: '2020_performance.com',
    utm_term: 'imgae1',
    utm_content: '1234325',
    utm_memo: 'utm 필요dsf하다',
    full_url: 'https://shop.com.ke',
    shorten_url: 'https://cococo.com',
  },
  {
    id: 3567457,
    created_at: '2023.02.24',
    utm_url: 'www.nn.com',
    utm_campaign_id: 'camapign ID',
    utm_source: 'sceedce',
    utm_medium: 'medium',
    utm_campaign_name: '2020_performance.com',
    utm_term: 'imgae1',
    utm_content: '1234325',
    utm_memo: 'utm 필요dsf하다',
    full_url: 'https://shop.com.ke',
    shorten_url: 'https://cococo.com',
  },
  {
    id: 309988,
    created_at: '2023.02.24',
    utm_url: 'www.nn.com',
    utm_campaign_id: 'camapign ID',
    utm_source: 'sceedce',
    utm_medium: 'medium',
    utm_campaign_name: '2020_performance.com',
    utm_term: 'imgae1',
    utm_content: '1234325',
    utm_memo: 'utm 필요dsf하다',
    full_url: 'https://shop.com.ke',
    shorten_url: 'https://cococo.com',
  },
  {
    id: 3565,
    created_at: '2023.02.24',
    utm_url: 'www.nn.com',
    utm_campaign_id: 'camapign ID',
    utm_source: 'sceedce',
    utm_medium: 'medium',
    utm_campaign_name: '2020_performance.com',
    utm_term: 'imgae1',
    utm_content: '1234325',
    utm_memo: 'utm 필요dsf하다',
    full_url: 'https://shop.com.ke',
    shorten_url: 'https://cococo.com',
  },
  {
    id: 3,
    created_at: '2023.02.24',
    utm_url: 'www.nn.com',
    utm_campaign_id: 'camapign ID',
    utm_source: 'sceedce',
    utm_medium: 'medium',
    utm_campaign_name: '2020_performance.com',
    utm_term: 'imgae1',
    utm_content: '1234325',
    utm_memo: 'utm 필요dsf하다',
    full_url: 'https://shop.com.ke',
    shorten_url: 'https://cococo.com',
  },
  {
    id: 3254325,
    created_at: '2023.02.24',
    utm_url: 'www.nn.com',
    utm_campaign_id: 'camapign ID',
    utm_source: 'sceedce',
    utm_medium: 'medium',
    utm_campaign_name: '2020_performance.com',
    utm_term: 'imgae1',
    utm_content: '1234325',
    utm_memo: 'utm 필요dsf하다',
    full_url: 'https://shop.com.ke',
    shorten_url: 'https://cococo.com',
  },
  {
    id: 3245336,
    created_at: '2023.02.24',
    utm_url: 'www.nn.com',
    utm_campaign_id: 'camapign ID',
    utm_source: 'sceedce',
    utm_medium: 'medium',
    utm_campaign_name: '2020_performance.com',
    utm_term: 'imgae1',
    utm_content: '1234325',
    utm_memo: 'utm 필요dsf하다',
    full_url: 'https://shop.com.ke',
    shorten_url: 'https://cococo.com',
  },
  {
    id: 3,
    created_at: '2023.02.24',
    utm_url: 'www.nn.com',
    utm_campaign_id: 'camapign ID',
    utm_source: 'sceedce',
    utm_medium: 'medium',
    utm_campaign_name: '2020_performance.com',
    utm_term: 'imgae1',
    utm_content: '1234325',
    utm_memo: 'utm 필요dsf하다',
    full_url: 'https://shop.com.ke',
    shorten_url: 'https://cococo.com',
  },
  {
    id: 3,
    created_at: '2023.02.24',
    utm_url: 'www.nn.com',
    utm_campaign_id: 'camapign ID',
    utm_source: 'sceedce',
    utm_medium: 'medium',
    utm_campaign_name: '2020_performance.com',
    utm_term: 'imgae1',
    utm_content: '1234325',
    utm_memo: 'utm 필요dsf하다',
    full_url: 'https://shop.com.ke',
    shorten_url: 'https://cococo.com',
  },
  {
    id: 3,
    created_at: '2023.02.24',
    utm_url: 'www.nn.com',
    utm_campaign_id: 'camapign ID',
    utm_source: 'sceedce',
    utm_medium: 'medium',
    utm_campaign_name: '2020_performance.com',
    utm_term: 'imgae1',
    utm_content: '1234325',
    utm_memo: 'utm 필요dsf하다',
    full_url: 'https://shop.com.ke',
    shorten_url: 'https://cococo.com',
  },
  {
    id: 3,
    created_at: '2023.02.24',
    utm_url: 'www.nn.com',
    utm_campaign_id: 'camapign ID',
    utm_source: 'sceedce',
    utm_medium: 'medium',
    utm_campaign_name: '2020_performance.com',
    utm_term: 'imgae1',
    utm_content: '1234325',
    utm_memo: 'utm 필요dsf하다',
    full_url: 'https://shop.com.ke',
    shorten_url: 'https://cococo.com',
  },
  {
    id: 3324,
    created_at: '2023.02.24',
    utm_url: 'www.nn.com',
    utm_campaign_id: 'camapign ID',
    utm_source: 'sceedce',
    utm_medium: 'medium',
    utm_campaign_name: '2020_performance.com',
    utm_term: 'imgae1',
    utm_content: '1234325',
    utm_memo: 'utm 필요dsf하다',
    full_url: 'https://shop.com.ke',
    shorten_url: 'https://cococo.com',
  },
  {
    id: 3123,
    created_at: '2023.02.24',
    utm_url: 'www.nn.com',
    utm_campaign_id: 'camapign ID',
    utm_source: 'sceedce',
    utm_medium: 'medium',
    utm_campaign_name: '2020_performance.com',
    utm_term: 'imgae1',
    utm_content: '1234325',
    utm_memo: 'utm 필요dsf하다',
    full_url: 'https://shop.com.ke',
    shorten_url: 'https://cococo.com',
  },
  {
    id: 3324,
    created_at: '2023.02.24',
    utm_url: 'www.nn.com',
    utm_campaign_id: 'camapign ID',
    utm_source: 'sceedce',
    utm_medium: 'medium',
    utm_campaign_name: '2020_performance.com',
    utm_term: 'imgae1',
    utm_content: '1234325',
    utm_memo: 'utm 필요dsf하다',
    full_url: 'https://shop.com.ke',
    shorten_url: 'https://cococo.com',
  },
  {
    id: 3324,
    created_at: '2023.02.24',
    utm_url: 'www.nn.com',
    utm_campaign_id: 'camapign ID',
    utm_source: 'sceedce',
    utm_medium: 'medium',
    utm_campaign_name: '2020_performance.com',
    utm_term: 'imgae1',
    utm_content: '1234325',
    utm_memo: 'utm 필요dsf하다',
    full_url: 'https://shop.com.ke',
    shorten_url: 'https://cococo.com',
  },
  {
    id: 3324,
    created_at: '2023.02.24',
    utm_url: 'www.nn.com',
    utm_campaign_id: 'camapign ID',
    utm_source: 'sceedce',
    utm_medium: 'medium',
    utm_campaign_name: '2020_performance.com',
    utm_term: 'imgae1',
    utm_content: '1234325',
    utm_memo: 'utm 필요dsf하다',
    full_url: 'https://shop.com.ke',
    shorten_url: 'https://cococo.com',
  },
  {
    id: 3324,
    created_at: '2023.05.24',
    utm_url: 'www.nn.com',
    utm_campaign_id: 'camapign ID',
    utm_source: 'sceedce',
    utm_medium: 'medium',
    utm_campaign_name: '2020_performance.com',
    utm_term: 'imgae1',
    utm_content: '1234325',
    utm_memo: 'utm 필요dsf하다',
    full_url: 'https://shop.com.ke',
    shorten_url: 'https://cococo.com',
  },
  {
    id: 3324,
    created_at: '2023.03.24',
    utm_url: 'www.nn.com',
    utm_campaign_id: 'camapign ID',
    utm_source: 'sceedce',
    utm_medium: 'medium',
    utm_campaign_name: '2020_performance.com',
    utm_term: 'imgae1',
    utm_content: '1234325',
    utm_memo: 'utm 필요dsf하다',
    full_url: 'https://shop.com.ke',
    shorten_url: 'https://cococo.com',
  },
  {
    id: 3324,
    created_at: '2023.04.24',
    utm_url: 'www.nn.com',
    utm_campaign_id: 'camapign ID',
    utm_source: 'sceedce',
    utm_medium: 'medium',
    utm_campaign_name: '2020_performance.com',
    utm_term: 'imgae1',
    utm_content: '1234325',
    utm_memo: 'utm 필요dsf하다',
    full_url: 'https://shop.com.ke',
    shorten_url: 'https://cococo.com',
  },
  {
    id: 4,
    created_at: '2023.02.25',
    utm_url: 'www.vava.com',
    utm_campaign_id: 'camapign ID',
    utm_source: 'sceedce',
    utm_medium: 'medium',
    utm_campaign_name: '2020_performance.com',
    utm_term: 'imgae1',
    utm_content: '1234325',
    utm_memo: 'utm 필요dsf하다',
    full_url: 'https://shop.com.ke',
    shorten_url: 'https://cococo.com',
  },
  {
    id: 5,
    created_at: '2023.02.26',
    utm_url: 'www.vava.com',
    utm_campaign_id: 'camapign ID',
    utm_source: 'sceedce',
    utm_medium: 'medium',
    utm_campaign_name: '2020_performance.com',
    utm_term: 'imgae1',
    utm_content: '1234325',
    utm_memo: 'utm 필요dsf하다',
    full_url: 'https://shop.com.ke',
    shorten_url: 'https://cococo.com',
  },
  {
    id: 6,
    created_at: '2023.02.27',
    utm_url: 'www.vava.com',
    utm_campaign_id: 'camapign ID',
    utm_source: 'sceedce',
    utm_medium: 'medium',
    utm_campaign_name: '2020_performance.com',
    utm_term: 'imgae1',
    utm_content: '1234325',
    utm_memo: 'utm 필요dsf하다',
    full_url: 'https://shop.com.ke',
    shorten_url: 'https://cococo.com',
  },
  {
    id: 7,
    created_at: '2023.03.01',
    utm_url: 'www.vava.com',
    utm_campaign_id: 'camapign ID',
    utm_source: 'sceedce',
    utm_medium: 'medium',
    utm_campaign_name: '2020_performance.com',
    utm_term: 'imgae1',
    utm_content: '1234325',
    utm_memo: 'utm 필요dsf하다',
    full_url: 'https://shop.com.ke',
    shorten_url: 'https://cococo.com',
  },
  {
    id: 8,
    created_at: '2023.02.02',
    utm_url: 'www.vava.com',
    utm_campaign_id: 'camapign ID',
    utm_source: 'sceedce',
    utm_medium: 'medium',
    utm_campaign_name: '2020_performance.com',
    utm_term: 'imgae1',
    utm_content: '1234325',
    utm_memo: 'utm 필요dsf하다',
    full_url: 'https://shop.com.ke',
    shorten_url: 'https://cococo.com',
  },
  {
    id: 9,
    created_at: '2023.03.03',
    utm_url: 'www.vava.com',
    utm_campaign_id: 'camapign ID',
    utm_source: 'sceedce',
    utm_medium: 'medium',
    utm_campaign_name: '2020_performance.com',
    utm_term: 'imgae1',
    utm_content: '1234325',
    utm_memo: 'utm 필요dsf하다',
    full_url: 'https://shop.com.ke',
    shorten_url: 'https://cococo.com',
  },
  {
    id: 10,
    created_at: '2023.04.01',
    utm_url: 'www.vava.com',
    utm_campaign_id: 'camapign ID',
    utm_source: 'sceedce',
    utm_medium: 'medium',
    utm_campaign_name: '2020_performance.com',
    utm_term: 'imgae1',
    utm_content: '1234325',
    utm_memo: 'utm 필요dsf하다',
    full_url: 'https://shop.com.ke',
    shorten_url: 'https://cococo.com',
  },
  {
    id: 11,
    created_at: '2023.03.05',
    utm_url: 'www.vava.com',
    utm_campaign_id: 'camapign ID',
    utm_source: 'sceedce',
    utm_medium: 'medium',
    utm_campaign_name: '2020_performance.com',
    utm_term: 'imgae1',
    utm_content: '1234325',
    utm_memo: 'utm 필요dsf하다',
    full_url: 'https://shop.com.ke',
    shorten_url: 'https://cococo.com',
  },
];

//get, api/utms
// export async function getUtmList():MainTableType[]{
//   return
// }

//delete, api/utms/delete/id
export function removeUtm() {}

//patch, api/utm/memo, id, memo
export function patchUtmMemo() {}

//post, api/utm/add
export function addUtm() {}

//post, api/utms/excell
export function outputUtm() {}

//post, api/utms
export function createUtm() {}
